remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Readme.en.md
  - vi/Tutorial-Windows.md
  - vi/Tutorial-Linux.md
  - vi/Tutorial-macOS.md
